### ISSUE TITLE
Need to call out OSes close to EoL and add in new

### ISSUE THREAD

**Issue by mckraken** [rackerlabs/docs-aws#43]
docs/service-levels/index.rst

The following OSes will be EoL soon and should be called out in the docs as such:
RHEL 6 - November 2020
CentOS 6 - November 2020
Amazon Linux (legacy) - December 2020
Ubuntu 16.04 - April 2021

We also now support Ubuntu 20.04

**Comment by stephamon** [comment]
Will do, thanks @mckraken

**Comment by mckraken** [comment]
@stephamon when will this be done?   Ubuntu 20.04 should be put in already as supported.

**Comment by mckraken** [comment]
The other OSes that are not coming close to EoL are:
```
Currently Supported Linux Operating Systems:
- Amazon Linux 2 supported until June 30, 2023
- RHEL or CentOS 7 supported until June 30, 2024
- RHEL or CentOS 8 supported until May, 2029
- Ubuntu 16.04 LTS supported until April 30, 2021
- Ubuntu 18.04 LTS supported until April 30, 2023
- Ubuntu 20.04 LTS supported until April 30, 2025
```
