### ISSUE TITLE
Logbook doc has a "temporary bastion," reference

### ISSUE THREAD

**Issue by cloudnativeengineer** [rackerlabs/docs-aws#44]
The Logbook doc has a "temporary bastion," reference that should be removed.

https://developer.rackspace.com/docs/fanatical-support-aws/logbook/

- Fanatical Support for AWS environment access: any time a Racker or one of your employees accesses your AWS environment by creating an access request and **provisioning a temporary bastion**, view the specific resources they had access to, the source of their access request, and other associated details throughout the duration of the access request

**Comment by stephamon** [comment]
Hey @cloudnativeengineer should I just remove that part like: "... by creating an access request, view the specific resources they had access to..."?

**Comment by cloudnativeengineer** [comment]
How about this?

Fanatical Support for AWS environment access: any time a Racker, or one of your employees, accesses your AWS environment by creating a [Passport access request,](https://developer.rackspace.com/docs/fanatical-support-aws/passport/) you may view the specific instances they had access to, the source of their Passport access request, and other associated details throughout the duration of the Passport access request.

**Comment by stephamon** [comment]
Perfect, thank you!
