### ISSUE TITLE
Remove references to rackspace-passport-bastion in Account Defaults

### ISSUE THREAD

**Issue by cloudnativeengineer** [rackerlabs/docs-aws#52]
Now that Passport V2 has been released, the [Account Defaults documentation](https://github.com/rackerlabs/docs-aws/blob/master/docs/aws-accounts/account-defaults.rst) needs to be updated to remove references to rackspace-passport-bastion.

- Create an IAM role named "rackspace-passport-bastion" with an IAM policy that allows bastion logs to be written to CloudWatch Logs.

- Create an EC2 Instance Profile named "rackspace-passport-bastion-instance-profile" with the "rackspace-passport-bastion" role attached.

- Create a "rackspace-passport-bastion" CloudWatch Logs Group where logs are shipped for Rackspace operational purposes.

**Comment by stephamon** [comment]
I'm on it @cloudnativeengineer sorry for the delay. I don't get issue notifications in my email!
